print("Nhap vao so nguyen duong X: ")
x = int(input())
print("Nhap vao so nguyen duong Y: ")
y = int(input())
print("Nhap vao ky tu c :")
c = input() 
print("Nhap vao so thuc f :")
f = float(input())
print("Nhap vao so thuc d :")
d = float(input())
print ("x = ", x) 
print ("y = ", y)
print ("c = ", c)
print ("f = ", '%.2f' %f)
print ("d = ", '%.9f' %d) 